services:
  mysql:
    image: 'mysql:8'
    environment:
      MYSQL_DATABASE: payment_limits_db
      MYSQL_PASSWORD: Password1
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_USER: pl
    ports:
      - '3306:3306'
    volumes:
      - db:/data/db
    restart: always
volumes:
  db:
    driver: local
